#!/usr/bin/env python

import sys

from spice_selection_gui.spice_select import SpiceSelectionPlugin
from rqt_gui.main import Main

plugin = 'rqt_mypkg'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))